apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp-deployment
spec:
  selector:
    matchLabels:
      app: backapp
  replicas: 1
  template:
    metadata:
      labels:
        app: backapp
    spec:
      containers:
        - name: backapp
          image: backapp:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backapp-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080 # The port inside the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # Type of service
  selector:
    app: backapp
